name: info
on:
  push:
    paths-ignore:
      - '*.md'

jobs:
  msvc:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64]
        toolset: ['14.39', '14.40']
      fail-fast: false

    steps:
      - uses: actions/checkout@master
      - name: Test ${{ matrix.arch }} ${{ matrix.toolset }}
        shell: cmd
        run: |
          @call "%ProgramFiles%\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.arch }} -vcvars_ver=${{ matrix.toolset }}
          @set VCToolsVersion
          cl typeof.c /std:clatest
          typeof.exe
